version: 2

#registries:
#  clas12maven:
#    type: maven-repository
#    url: https://clasweb.jlab.org/clas12maven
#  jhep:
#    type: maven-repository
#    url: https://clasweb.jlab.org/jhep/maven

updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - clas12maven
      - jhep
    ignore:
      - dependency-name: "org.jlab:groot" # since version numbers are not in order
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
