version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.jlab:groot" # since version numbers are not in order
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
