package org.hps.recon.mdc;

import java.io.File;
import java.io.IOException;
import java.net.URL;

import junit.framework.TestCase;

import org.lcsim.job.JobControlManager;
import org.lcsim.util.cache.FileCache;

/**
 * This test runs the standard reconstruction on a small set of Mock Data events
 * generated by the trigger simulation.
 * 
 * @author Jeremy McCormick <jeremym@slac.stanford.edu>
 */
public class MockDataReconTest extends TestCase {
    
    static final String mockDataUrl = 
            "http://www.slac.stanford.edu/~meeg/hps2/meeg/mock_data/tritrig-beam-tri_1-10_readout.slcio";
    
    public void testReconMockData() {
        
        File mockDataFile = null;
        try {
            FileCache cache = new FileCache();
            mockDataFile = cache.getCachedFile(new URL(mockDataUrl));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        
        JobControlManager jobManager = new JobControlManager();
        jobManager.addVariableDefinition("outputFile", "target/" + this.getClass().getSimpleName());
        jobManager.addInputFile(mockDataFile);
        jobManager.setup("/org/hps/steering/recon/MockDataReconTest.lcsim");
        jobManager.run();
    }
}
