name: build

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          server-id: github

      - name: Build
        run: |
          mvn -B install -DskipTests=true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
