name: release version

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v3  

    - name: Build and Test
      uses: qcastel/github-actions-maven-cmd@master
      with:
        maven-args: "clean install -DskipTests"

    - name: Release
      uses: qcastel/github-actions-maven-release@master
      env:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
      with:
        maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Dmaven.deploy.skip=true"