name: test

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          server-id: github

      - name: Build and run tests
        run: |
          mvn -B install -T4
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
